backend:
  name: backend
  build: .
  ports:
   - "5000:5000"
  volumes:
   - .:/code
  links:
   - redis
   - mongo
redis:
  image: redis
mongo:
  image: mongo
  ports:
    - "27017:27017"
frontend:
  image: frontend
  ports:
    - "8080:80"
  environment:
    - SITE_NAME=e.slamar.com
    - NGINX_PORT=80
    - BACKEND_HOST=backend
    - BACKEND_PORT=5000
  links:
    - backend
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/backend-proxy.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
